package yash.Projects.GuessNumber;

import javax.swing.*;
import javax.swing.border.Border;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;

public class NumberGuess extends JFrame implements ActionListener {
    JButton submit,playAgain,exit;
    JLabel computerMessage,instruction,gameMessage,turn;
    JTextField playerNumberField;
    JTextField computerNumberField;

    int computerNumber,playerNumber,turnsRemaining;
    static int roundNumber;
    NumberGuess(){
        // using roundNumber to keep track of number of rounds Played
        // It is used so that the instructions are only generated once.
        roundNumber ++;

        // Displaying the game rules only once in the beginning of the game.
        if(roundNumber==1){
            JOptionPane.showMessageDialog(this, """
                            Welcome to Number Guessing Game.
                            You have to guess a number generated by the Computer.
                            For each Round You get 10 chances to guess the correct number.""",
                    "Game Rules", JOptionPane.INFORMATION_MESSAGE);
        }

        Random random = new Random();
        computerNumber = random.nextInt(1,101);
        turnsRemaining = 10;

        setTitle("Number Guessing Game");
        setSize(400,650);
        setLayout(null);


        computerMessage = new JLabel();
        computerMessage.setText("Computer's Number");
        computerMessage.setFont(new Font(Font.DIALOG,Font.BOLD,25));
        computerMessage.setHorizontalAlignment(SwingConstants.CENTER);
        computerMessage.setBounds(30,10,320,40);
        computerMessage.setForeground(new Color(0, 115, 255));

        computerNumberField = new JTextField();
        computerNumberField.setText("Guess the Number ?");
        computerNumberField.setEditable(false);
        computerNumberField.setFont(new Font(Font.DIALOG,Font.BOLD,30));
        computerNumberField.setHorizontalAlignment(SwingConstants.CENTER);
        computerNumberField.setBounds(30,70,320,60);

        instruction = new JLabel();
        instruction.setText("Enter your number Below");
        instruction.setFont(new Font(Font.DIALOG,Font.BOLD,25));
        instruction.setHorizontalAlignment(SwingConstants.CENTER);
        instruction.setBounds(30,170,320,40);
        instruction.setForeground(new Color(0, 115, 255));

        playerNumberField = new JTextField("");
        playerNumberField.setFont(new Font(Font.DIALOG,Font.BOLD,30));
        playerNumberField.setBounds(30,230,320,60);
        playerNumberField.setHorizontalAlignment(SwingConstants.CENTER);


        submit = new JButton("SUBMIT");
        submit.setBounds(115,300,150,40);
        submit.setFont(new Font(Font.DIALOG,Font.BOLD,25));
        submit.setHorizontalAlignment(SwingConstants.CENTER);
        submit.addActionListener(this);
        submit.setEnabled(true);
        submit.setFocusable(false);

        turn = new JLabel();
        turn.setText("Turns Remaining : " + turnsRemaining);
        turn.setFont(new Font(Font.DIALOG,Font.BOLD,25));
        turn.setHorizontalAlignment(SwingConstants.CENTER);
        turn.setBounds(30,370,320,40);
        turn.setForeground(new Color(204, 68, 83));

        gameMessage = new JLabel();
        gameMessage.setText("Guess The Number");
        gameMessage.setFont(new Font(Font.DIALOG,Font.BOLD,25));
        gameMessage.setHorizontalAlignment(SwingConstants.CENTER);
        gameMessage.setBounds(30,430,320,40);
        gameMessage.setForeground(new Color(243, 170, 39));

        playAgain = new JButton("Play Again");
        playAgain.setBounds(30,530,145,40);
        playAgain.setFont(new Font(Font.DIALOG,Font.BOLD,21));
        playAgain.setForeground(new Color(17, 16, 16));
        playAgain.setBackground(new Color(72, 189, 42));
        playAgain.setEnabled(false);
        playAgain.addActionListener(this);

        exit = new JButton("Exit");
        exit.setBounds(200,530,145,40);
        exit.setFont(new Font(Font.DIALOG,Font.BOLD,24));
        exit.setForeground(new Color(17, 16, 16));
        exit.setBackground(new Color(229, 72, 72));
        exit.setEnabled(false);
        exit.addActionListener(this);

        add(computerMessage);
        add(computerNumberField);
        add(instruction);
        add(playerNumberField);
        add(submit);
        add(turn);
        add(gameMessage);
        add(playAgain);
        add(exit);

        // Used so that the window appears on the centre of the screen
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setVisible(true);
    }


    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == submit){
            turnsRemaining--;
            turn.setText("Turns Remaining : " + turnsRemaining);
            // Getting user Entered number
            playerNumber = Integer.parseInt(playerNumberField.getText());

            if (turnsRemaining > 0){
                if (computerNumber == playerNumber){
                    playAgain.setEnabled(true);
                    exit.setEnabled(true);
                    submit.setEnabled(false);
                    playerNumberField.setEditable(false);
                    gameMessage.setForeground(new Color(3, 115, 3));
                    computerNumberField.setText(String.valueOf(computerNumber));
                    gameMessage.setText("You Got it Correct !!");
                } else if (computerNumber < playerNumber) {
                    gameMessage.setText("Number too high");
                    playerNumberField.setText("");
                } else {
                    gameMessage.setText("Number too Low");
                    playerNumberField.setText("");
                }
            }else{
                // Enabling PlayAgain and Exit buttons in case of last chance
                submit.setEnabled(false);
                playAgain.setEnabled(true);
                exit.setEnabled(true);
                playerNumberField.setEditable(false);

                // Displaying the Computer generated number to Verify
                computerNumberField.setText(String.valueOf(computerNumber));

                if (computerNumber == playerNumber){
                    gameMessage.setForeground(new Color(3, 115, 3));
                    gameMessage.setText("You Got it Correct !!");
                }else{
                    gameMessage.setForeground(new Color(255, 0, 0));
                    gameMessage.setText("You Lost the Game");
                }
            }
        }

        if (e.getSource() == playAgain){
            this.dispose();
            new NumberGuess();
        }

        if (e.getSource() == exit){
            JOptionPane.showMessageDialog(this, "Thank You for Playing",
                    "Greetings", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
    }


    public static void main(String[] args) {
        new NumberGuess();
    }
}